### ISSUE TITLE
Use consistent shapes of the observed proportions

### ISSUE THREAD

**Issue by pawel-czyz** [cbg-ethz/covvfit#24]
Currently, we keep the observed proportions either as:

1.  An array with shape `(n_timepoints, n_variants)` or 
2. An array with shape `(n_variants, n_timepoints)`.

The problem is that:
1. Different submodules use different convention (e.g., quasimultinomial and plotting submodules).
2. In fact, quasimultinomial submodule uses both conventions simultaneously!

As this is *very* counterintuitive and can lead to annoying bugs down the line (e.g., when calculating overdispersion), I'm annotating it as `bug`, rather than `refactor`.

**Comment by dr-david** [comment]
Indeed. Should we do ```n_timepoints t_timepoints``` ?

**Comment by pawel-czyz** [comment]
@dr-david I'm working on this (but only on the public API), so that we will have more consistent user experience in our notebooks. (Well, *the* notebook, actually: we now officially support only [`frequentist_notebook_jax`](https://github.com/cbg-ethz/covvfit/blob/main/examples/frequentist_notebook_jax.py), but we have some notebooks which have not been officially added yet, but implement very nice prototypes.)

The PR will spread across quite many files (what's not great for reviewing, but I don't see another solution) and I hope it'll be ready on Wednesday.
